FROM python:3.9.5

ARG ARG_DATA_MODEL=""
ARG ARG_REPOSITORY_NAME=""
ARG ARG_ROOT_MODEL_URL=""
ARG ARG_REPO_FOLDER=""
ARG ARG_OUTPUT_FILENAME=""
ARG ARG_WORKDIR="/github/workspace"

ENV DATA_MODEL=${ARG_DATA_MODEL}
ENV REPOSITORY_NAME=${ARG_REPOSITORY_NAME}
ENV ROOT_MODEL_URL=${ARG_ROOT_MODEL_URL}
ENV MODEL_FOLDER=${ARG_REPO_FOLDER}/${ARG_DATA_MODEL}
ENV OUTPUT_FILENAME=${ARG_OUTPUT_FILENAME}

WORKDIR ${ARG_WORKDIR}

COPY . .

RUN mkdir model-folder/
RUN pip install --no-cache-dir -r requirements.txt

CMD ["build-yaml.py"]

ENTRYPOINT ["python3"]